In [1]:
import numpy as np
import csv
import matplotlib.pyplot as plt
import random
import tensorflow as tf
#from bayes_opt import BayesianOptimization
from skopt import gp_minimize
from skopt.space import Real, Integer
from functools import partial
import requests #for the API

2025-02-08 18:10:28.787632: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [1]:
import requests #for the API

In [2]:
overall_dict = {}

overall_dict["Fat"] = 0
overall_dict["Saturated fatty acids"] = 0
overall_dict["Fatty acids, total trans"] = 0
overall_dict["Cholesterol"] = 0
overall_dict["Sodium"] = 0
overall_dict["Carbohydrate"] = 0
overall_dict["Fiber"] = 0
overall_dict["Sugars"] = 0
overall_dict["Protein"] = 0
overall_dict["Calcium"] = 0
overall_dict["Iron"] = 0
overall_dict["Potassium"] = 0
overall_dict["Vitamin D"] = 0
overall_dict["Weight"] = 0
overall_dict["Calories"] = 0

In [3]:
tates_dict = overall_dict.copy()
tates_dict["Fat"] = 7
tates_dict["Saturated fatty acids"] = 4.5
tates_dict["Fatty acids, total trans"] = 0
tates_dict["Cholesterol"] = .025
tates_dict["Sodium"] = .16
tates_dict["Carbohydrate"] = 18
tates_dict["Fiber"] = .8
tates_dict["Sugars"] = 12
tates_dict["Protein"] = 2
tates_dict["Calcium"] = .0000001
tates_dict["Iron"] = .0009
tates_dict["Potassium"] = .01
tates_dict["Vitamin D"] = .05
tates_dict["Weight"] = 28
tates_dict["Calories"] = 140

In [4]:
natural_vanilla_dict = overall_dict.copy()
#calories per 10 grams: 27 
natural_vanilla_dict["Fat"] = 0
natural_vanilla_dict["Saturated fatty acids"] = 0
natural_vanilla_dict["Fatty acids, total trans"] = 0
natural_vanilla_dict["Cholesterol"] = 0
natural_vanilla_dict["Sodium"] = .04 / 1000
natural_vanilla_dict["Carbohydrate"] = 1.2
natural_vanilla_dict["Fiber"] = 0
natural_vanilla_dict["Sugars"] = 0
natural_vanilla_dict["Protein"] = 0
natural_vanilla_dict["Calcium"] = 0
natural_vanilla_dict["Iron"] = 0
natural_vanilla_dict["Potassium"] = 0
natural_vanilla_dict["Vitamin D"] = 0
natural_vanilla_dict["Weight"] = 10
natural_vanilla_dict["Calories"] = 27

baking_soda_alex_dict = overall_dict.copy()
#calories per 10 grams: 0
baking_soda_alex_dict["Fat"] = 0
baking_soda_alex_dict["Saturated fatty acids"] = 0
baking_soda_alex_dict["Fatty acids, total trans"] = 0
baking_soda_alex_dict["Cholesterol"] = 0
baking_soda_alex_dict["Sodium"] = 2.736
baking_soda_alex_dict["Carbohydrate"] = 0
baking_soda_alex_dict["Fiber"] = 0
baking_soda_alex_dict["Sugars"] = 0
baking_soda_alex_dict["Protein"] = 0
baking_soda_alex_dict["Calcium"] = 0
baking_soda_alex_dict["Iron"] = 0
baking_soda_alex_dict["Potassium"] = 0
baking_soda_alex_dict["Vitamin D"] = 0
baking_soda_alex_dict["Weight"] = 10
baking_soda_alex_dict["Calories"] = 0

In [3]:
api_key = "pJdDYwC0EdXMpR18wMXFqjMxO4zYGCuTOfNfCSH4"
query = "unbleached flour"
url = f"https://api.nal.usda.gov/fdc/v1/foods/search?query={query}&dataType=Foundation&api_key={api_key}"

response = requests.get(url)
data = response.json()

if data['foods']:
    print("Showing results from Foundation Foods:")
else:
    print("No Foundation Foods found. Searching Branded Foods...")
    url = f"https://api.nal.usda.gov/fdc/v1/foods/search?query={query}&dataType=Branded&api_key={api_key}"
    response = requests.get(url)
    data = response.json()

# Print the first 5 results
for food in data['foods'][:5]:
    print(f"Name: {food['description']}")
    print(f"FDC ID: {food['fdcId']}")
    print("-" * 30)

Showing results from Foundation Foods:
Name: Flour, pastry, unenriched, unbleached
FDC ID: 1104913
------------------------------
Name: Flour, bread, white, enriched, unbleached
FDC ID: 790146
------------------------------
Name: Flour, wheat, all-purpose, enriched, unbleached
FDC ID: 789951
------------------------------
Name: Flour, wheat, all-purpose, unenriched, unbleached
FDC ID: 790018
------------------------------
Name: Flour, 00
FDC ID: 2003586
------------------------------


In [ ]:
overall_dict1 = {}

overall_dict1["Total lipid (fat)"] = 0
overall_dict1["Saturated fatty acids"] = 0
overall_dict1["Fatty acids, total trans"] = 0
overall_dict1["Cholesterol"] = 0
overall_dict1["Sodium, Na"] = 0
overall_dict1["Carbohydrate"] = 0
overall_dict1["Fiber"] = 0
overall_dict1["Sugars"] = 0
overall_dict1["Protein"] = 0
overall_dict1["Calcium, Ca"] = 0
overall_dict1["Iron, Fe"] = 0
overall_dict1["Potassium, K"] = 0
overall_dict1["Vitamin D"] = 0
overall_dict1["Water"] = 0
overall_dict1["Weight"] = 0
overall_dict1['Energy"] = 0

In [6]:
fdc_id = data['foods'][0]['fdcId']
nutrition_url = f"https://api.nal.usda.gov/fdc/v1/food/{fdc_id}?api_key={api_key}"

response = requests.get(nutrition_url)
nutrition_data = response.json()

# Print nutrient details
for nutrient in nutrition_data['foodNutrients']:
    print(f"{nutrient['nutrient']['name']}")
    amount = nutrient.get("amount","NA")
    unit = nutrient.get("nutrient", {}).get("unitName", "")
    print(amount,unit)
    all_purpy_dict = oerall_dict1.copy()
    for key in all_purpy_dict:
        if key in nutrition_data['foodNutrients']

Proximates
NA g
Water
11.9 g
Energy
358.0 kcal
Energy
1500.0 kJ
Nitrogen
1.4 g
Protein
8.75 g
Total lipid (fat)
1.64 g
Ash
0.53 g
Carbohydrates
NA g
Carbohydrate, by difference
77.2 g
Minerals
NA mg
Calcium, Ca
17.0 mg
Iron, Fe
0.87 mg
Magnesium, Mg
22.4 mg
Phosphorus, P
102.0 mg
Potassium, K
142.0 mg
Sodium, Na
1.0 mg
Zinc, Zn
0.74 mg
Copper, Cu
0.159 mg
Manganese, Mn
0.635 mg
Selenium, Se
5.0 µg
Molybdenum, Mo
59.1 µg
Vitamins and Other Components
NA g
Thiamin
0.146 mg
Riboflavin
0.0 mg
Niacin
0.988 mg
Vitamin B-6
0.065 mg


In [21]:
ingredient_dict = overall_dict.copy()

def reader(file,ingredient_dict):
    with open(file, 'r') as csvfile:
        csvreader = csv.reader(csvfile)
        for i,row in enumerate(csvreader):
            if len(row) > 0 and row[0] in ingredient_dict:
                if row[2] == "mg":
                    ingredient_dict[row[0]] = (float(row[1]) / 1000)
                elif row[2] == "mcg":
                    ingredient_dict[row[0]] = (float(row[1]) / 1000000)
                else: #grams
                    ingredient_dict[row[0]] = (float(row[1]))
            if i == 4:
                index = row.index("g")
                ingredient_dict["Weight"] = float(row[index-1])
    return ingredient_dict

In [47]:
semi_sweet_chocolate_file = "semisweet_chocolate_chips_by_raleys.csv"
semi_sweet_chocolate_dict = overall_dict.copy()
reader(semi_sweet_chocolate_file,semi_sweet_chocolate_dict)


#need to change this.
unbleached_flour_file = "flour_unbleached_enriched_allpurpose_wheat.csv"
unbleached_flour_dict = overall_dict.copy()
reader(unbleached_flour_file,unbleached_flour_dict)
unbleached_flour_dict["Protein"] = .875

salted_butter_file = "butter_salted.csv"
salted_butter_dict = overall_dict.copy()
reader(salted_butter_file,salted_butter_dict)

cane_sugar_file = "granulated_pure_cane_sugar.csv"
cane_sugar_dict = overall_dict.copy()
reader(cane_sugar_file,cane_sugar_dict)

brown_cane_sugar_file = "brown_sugar_cane_by_frusecha.csv"
brown_cane_sugar_dict = overall_dict.copy()
reader(brown_cane_sugar_file,brown_cane_sugar_dict)

eggs_file = "egg_fresh_raw_whole.csv"
eggs_dict = overall_dict.copy()
reader(eggs_file,eggs_dict)

baking_soda_file = "leavening_agents_baking_soda.csv"
baking_soda_dict = overall_dict.copy()
reader(baking_soda_file,baking_soda_dict)

salt_file = "salt_table.csv"
salt_dict = overall_dict.copy()
reader(salt_file,salt_dict)

natural_vanilla_flavor_file = "vanilla_flavoring_syrup_by_r_torre__coinc.csv"
natural_vanilla_flavor_dict = overall_dict.copy()
reader(natural_vanilla_flavor_file,natural_vanilla_flavor_dict)

vanilla_extract_file_1 = "vanilla_extract.csv"
vanilla_extract_dict_1 = overall_dict.copy()
reader(vanilla_extract_file_1,vanilla_extract_dict_1)

dictionary_list = [semi_sweet_chocolate_dict,unbleached_flour_dict,salted_butter_dict,cane_sugar_dict,brown_cane_sugar_dict,eggs_dict,baking_soda_alex_dict,salt_dict,natural_vanilla_dict]
heavy_dictionary_list = [semi_sweet_chocolate_dict,unbleached_flour_dict,salted_butter_dict,cane_sugar_dict,brown_cane_sugar_dict,eggs_dict]
key_list = ["Fat","Saturated fatty acids","Fatty acids, total trans","Cholesterol","Sodium","Carbohydrate","Fiber","Sugars","Protein","Calcium","Iron","Potassium","Vitamin D","Weight","Calories"]
key_list_wo_weight = ["Fat","Saturated fatty acids","Fatty acids, total trans","Cholesterol","Sodium","Carbohydrate","Fiber","Sugars","Protein","Calcium","Iron","Potassium","Vitamin D","Calories"]
key_list_wo_sodium_and_weight = ["Fat","Saturated fatty acids","Fatty acids, total trans","Cholesterol","Carbohydrate","Fiber","Sugars","Protein","Calcium","Iron","Potassium","Vitamin D","Calories"]

In [30]:
def building_x_list(number,dictionary_list):
    x_list = []
    for variable in range(0, len(dictionary_list)):
        x_list.append(number)
    return x_list

x_list = building_x_list(1,dictionary_list)

In [31]:
def equations(dictionary_list,x_list,desired_dict,key_list):
    list_of_equations = []
    for key in key_list:
        equation = 0
        for i,dictionary in enumerate(dictionary_list):
            equation = equation + (dictionary[key] * (x_list[i] / 10))
        list_of_equations.append(equation-(desired_dict[key]))
    return list_of_equations

In [32]:
def initialize_variables_tf(n,desired_dict):
    largest_weight = desired_dict["Weight"]

    initial_values = tf.random.uniform(shape=(n,), minval=0.0, maxval=largest_weight)
    initial_values = tf.sort(initial_values, direction='DESCENDING')

    initial_values = (initial_values * largest_weight) / tf.reduce_sum(initial_values)
    
    return tf.Variable(initial_values, trainable=True)

In [33]:
def loss_tf(variables_tf,predicted):

    error = tf.reduce_mean(tf.square(predicted))
    error = error +  5*(tf.reduce_sum(tf.square(tf.minimum(variables_tf, 0))))
    
    variables_tf_array = variables_tf.numpy()
    for i in range(0,len(variables_tf_array)-2):
        if variables_tf_array[i] - variables_tf_array[i + 1] < 0:
            error = error + ((variables_tf_array[i] - variables_tf_array[i + 1]) ** 2)

    return error

In [34]:
def running_tf(dictionary_list,target_dict,key_list):  
    #number of ingredients
    n = len(dictionary_list)
    #first guess
    variables_tf = initialize_variables_tf(n,target_dict)
    print(variables_tf)
    print(tf.reduce_sum(variables_tf).numpy())
    #the optimizer chosen: stochastic gradient descent. WHAT IF WE TRIED batch gradient descent here?
    #pros/cons: https://www.geeksforgeeks.org/difference-between-batch-gradient-descent-and-stochastic-gradient-descent/
    #whats the math behind this?
        #updates each variable. the variable is updated to be its value - 
        #the learning rate * the gradient of how much that variable affects the loss.
        #THIS PART IS DIFFERENT FROM MY PREVIOUS METHOD MATHEMATICALLY, but does the same thing
        #SHOW tests for learning rates. date the comments.
    optimizer = tf.keras.optimizers.SGD(learning_rate=.01)

# Training loop
    #redefines the variable 600 times. what number is OPTIMAL?
    for epoch in range(600):

        #the "with" allows for automatic differentiation. this means the with part locks in the operations. but here no gradients are calculated.
        with tf.GradientTape() as tape:
        
            predictions1 = equations(dictionary_list,variables_tf,target_dict,key_list)
            predictions = tf.convert_to_tensor(predictions1)
            loss = loss_tf(variables_tf,predictions)

        #gradients are computed here.
        gradients = tape.gradient(loss, [variables_tf])

        #apply these gradients, perform sgd on our variables (which are being updated) 
        optimizer.apply_gradients(zip(gradients, [variables_tf]))

        if epoch % 20 == 0:
            print((tf.reduce_sum(variables_tf).numpy()))
            print(f"Epoch {epoch}, Loss: {loss.numpy():.4f}, Variables: {variables_tf.numpy()}")

    return variables_tf.numpy().tolist()

In [49]:
running_tf(heavy_dictionary_list,tates_dict,key_list)

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=
array([6.581594 , 6.5568275, 5.165269 , 4.123789 , 3.200676 , 2.3718445],
      dtype=float32)>
28.000002
28.591248
Epoch 0, Loss: 21.5745, Variables: [6.6963167 6.644034  5.3370123 4.2186294 3.2900026 2.4052498]
31.435423
Epoch 20, Loss: 0.9200, Variables: [7.260479  7.0548596 6.208421  4.6763024 3.7162943 2.5190685]
31.442177
Epoch 40, Loss: 0.8734, Variables: [7.27774   7.0447955 6.2671804 4.6802044 3.7136467 2.45861  ]
31.375498
Epoch 60, Loss: 0.8436, Variables: [7.280595  7.0242476 6.3019147 4.6733437 3.7007856 2.3946135]
31.30925
Epoch 80, Loss: 0.8156, Variables: [7.2832737 7.0041666 6.333899  4.6674647 3.6888213 2.3316233]
31.245272
Epoch 100, Loss: 0.7893, Variables: [7.2861395 6.9848137 6.3638535 4.6627707 3.677958  2.2697349]
31.183483
Epoch 120, Loss: 0.7645, Variables: [7.289182  6.9661603 6.3919353 4.659166  3.6681144 2.2089248]
31.123768
Epoch 140, Loss: 0.7410, Variables: [7.292383 6.948177 6.418278 4.656553 3.

[7.382574558258057,
 6.669881820678711,
 6.739553451538086,
 4.730730056762695,
 3.5939579010009766,
 1.0210227966308594]

In [49]:
running_tf(heavy_dictionary_list,tates_dict,key_list_wo_sodium_or_weight)

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=
array([6.581594 , 6.5568275, 5.165269 , 4.123789 , 3.200676 , 2.3718445],
      dtype=float32)>
28.000002
28.591248
Epoch 0, Loss: 21.5745, Variables: [6.6963167 6.644034  5.3370123 4.2186294 3.2900026 2.4052498]
31.435423
Epoch 20, Loss: 0.9200, Variables: [7.260479  7.0548596 6.208421  4.6763024 3.7162943 2.5190685]
31.442177
Epoch 40, Loss: 0.8734, Variables: [7.27774   7.0447955 6.2671804 4.6802044 3.7136467 2.45861  ]
31.375498
Epoch 60, Loss: 0.8436, Variables: [7.280595  7.0242476 6.3019147 4.6733437 3.7007856 2.3946135]
31.30925
Epoch 80, Loss: 0.8156, Variables: [7.2832737 7.0041666 6.333899  4.6674647 3.6888213 2.3316233]
31.245272
Epoch 100, Loss: 0.7893, Variables: [7.2861395 6.9848137 6.3638535 4.6627707 3.677958  2.2697349]
31.183483
Epoch 120, Loss: 0.7645, Variables: [7.289182  6.9661603 6.3919353 4.659166  3.6681144 2.2089248]
31.123768
Epoch 140, Loss: 0.7410, Variables: [7.292383 6.948177 6.418278 4.656553 3.

[7.382574558258057,
 6.669881820678711,
 6.739553451538086,
 4.730730056762695,
 3.5939579010009766,
 1.0210227966308594]

In [37]:
running_tf(heavy_dictionary_list,tates_dict,key_list)

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=
array([7.569378  , 6.2830787 , 6.244275  , 4.2315645 , 3.244995  ,
       0.42670557], dtype=float32)>
27.999998
28.284037
Epoch 0, Loss: 5.0285, Variables: [7.624502  6.3252068 6.3255267 4.2777534 3.288414  0.442633 ]
29.661541
Epoch 20, Loss: 0.3267, Variables: [7.8978915  6.528777   6.723259   4.5114446  3.5046082  0.49556178]
29.67849
Epoch 40, Loss: 0.3209, Variables: [7.9090443  6.530411   6.7331247  4.5266175  3.514378   0.46491402]
29.659147
Epoch 60, Loss: 0.3164, Variables: [7.9130816 6.526765  6.7328205 4.5355897 3.5183911 0.4325016]
29.63899
Epoch 80, Loss: 0.3121, Variables: [7.916837  6.5231056 6.732438  4.544064  3.5220358 0.4005089]
29.61897
Epoch 100, Loss: 0.3080, Variables: [7.9205     6.5195737  6.7322283  4.5522118  3.5254688  0.36898747]
29.599125
Epoch 120, Loss: 0.3041, Variables: [7.924078  6.516173  6.732182  4.5600533 3.5287073 0.3379323]
29.579466
Epoch 140, Loss: 0.3004, Variables: [7.9275737 6.5129

KeyboardInterrupt: 

In [218]:
def add_noise(optimized_heavy_ingredients):
    optimized_w_noise = []
    for i in range(0,len(optimized_heavy_ingredients)):
        number = random.randint(1,2)
        if number == 1:
            optimized_w_noise.append(optimized_heavy_ingredients[i] - .1)
        else:
            optimized_w_noise.append(optimized_heavy_ingredients[i] + .1)
    return optimized_w_noise

In [203]:
def error_function_lighter(lighter_ingredients,optimized_heavy_ingredients):

    full_ingredients = np.concatenate((optimized_heavy_ingredients, lighter_ingredients))
    equations_list = equations(dictionary_list,full_ingredients,tates_dict,key_list_wo_weight)
    error = 0
    for i, equation in enumerate(equations_list):
        #if i == 4 or i == 5:
        #    error += equation ** 2
        #else:
        error += equation

    #gives the total carbs/fats/proteins as looks at the difference + targeted amount --> actual amount
    carbs = equations_list[5] + tates_dict["Carbohydrate"]
    fats = equations_list[0] + tates_dict["Fat"]
    proteins = equations_list[8] + tates_dict["Protein"]
    calorie_count = (carbs * 4) + (fats * 9) + (proteins * 4)
    #the 140 is tates specific
    difference_in_calories = ((calorie_count) - 140) ** 2

    #dividing by 100 here because otherwise the error is too high - leaves bayesian optimization to just choose lowest option for lightest ingredients
    error += (difference_in_calories / 10)   
    return abs(error)

In [207]:
def error_function_bayesian(lighter_ingredients, optimized_heavy_ingredients):
    return error_function_lighter(lighter_ingredients, optimized_heavy_ingredients)

# Map lighter ingredients to their indices
lighter_indices = [6, 7, 8]  # vanilla, baking soda, xanthan gum

# Define the search space for Bayesian Optimization using the indices
search_space = [
    Real(0.00001, 1, name=f"ingredient_{lighter_indices[0]}"),  # baking_soda
    Real(0.00001, 1, name=f"ingredient_{lighter_indices[1]}"),  # salt
    Real(0.00001, 1, name=f"ingredient_{lighter_indices[2]}")   # vanilla
]

def bayesiann(optimized_heavy_ingredients):
    print("Optimized heavy ingredients passed to bayesiann:")
    print(optimized_heavy_ingredients)

    error_function_fixed = partial(error_function_lighter, optimized_heavy_ingredients=optimized_heavy_ingredients)
    result = gp_minimize(
        func=error_function_fixed,
        dimensions=search_space,
        #number of combinations tried
        n_calls=50, #whats the best number for this?
        #setting to 10 random guesses first, allowing exploration before making "smarter decisions"
        n_random_starts=10,
        #410 doesn't matter (just my bday). convention is 42.
        #random state ensures that the random first combinations are the same for
        #each run: pros
            #Ensures repeatability (same experiment = same results).
            # if results change, it's not due to randomness.
            # Allows fair comparisons (changing only one parameter won't affect randomness).
        #random_state=410
    )
    optimized_lighter_ingredients = result.x
    print("Debug: Optimized lighter ingredients from Bayesian Optimization:")
    print(result.x)
    
    # Debug: Print the minimum error achieved
    print("Debug: Minimum error achieved:")
    print(result.fun)
    return optimized_lighter_ingredients

In [208]:
eh = [7.441051483154297,
 6.959020614624023,
 5.859490871429443,
 5.395391941070557,
 3.0771231651306152,
 0.9919356107711792]

In [209]:
bayesiann(eh)

Optimized heavy ingredients passed to bayesiann:
[7.441051483154297, 6.959020614624023, 5.859490871429443, 5.395391941070557, 3.0771231651306152, 0.9919356107711792]
Debug: Optimized lighter ingredients from Bayesian Optimization:
[0.6363032108069293, 1.0, 0.705995480456912]
Debug: Minimum error achieved:
0.00011706091778351801


[0.6363032108069293, 1.0, 0.705995480456912]

In [220]:
bayesiann(eh_w_noise)

Optimized heavy ingredients passed to bayesiann:
[7.731051483154296, 7.049020614624023, 5.7694908714294435, 5.4853919410705565, 3.187123165130615, 0.8819356107711792]
Debug: Optimized lighter ingredients from Bayesian Optimization:
[1e-05, 1e-05, 1e-05]
Debug: Minimum error achieved:
0.7043763552547555


[1e-05, 1e-05, 1e-05]

In [154]:
def reversy(dictionary_list_for_heavy,target_dict,key_list):

    optimized_heavy = running_tf(dictionary_list_for_heavy,target_dict,key_list)
    noisy_optimized = add_noise(optimized_heavy)
    lighter = bayesiann(noisy_optimized)

    return optimized_heavy, lighter
    

In [155]:
reversy(heavy_dictionary_list,tates_dict,key_list)

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=
array([7.640944 , 6.1839886, 5.6975045, 5.6498637, 2.257335 , 0.5703667],
      dtype=float32)>
28.000002
Optimized heavy ingredients passed to bayesiann:
[7.7850305938720705, 6.252763519287109, 5.657139053344727, 5.837734928131104, 2.373724689483643, 0.3693550431728363]
Debug: Optimized lighter ingredients from Bayesian Optimization:
[1e-05, 1.0, 1e-05]
Debug: Minimum error achieved:
0.007327536285742217


([7.7850305938720705,
  6.252763519287109,
  5.657139053344727,
  5.837734928131104,
  2.373724689483643,
  0.3693550431728363],
 [1e-05, 1.0, 1e-05])

In [166]:
smoothie_dict = overall_dict.copy()
smoothie_dict["Fat"] = 10.1
smoothie_dict["Saturated fatty acids"] = 2.5
smoothie_dict["Fatty acids, total trans"] = 0
smoothie_dict["Cholesterol"] = 10/1000
smoothie_dict["Sodium"] = 428.7/1000
smoothie_dict["Carbohydrate"] = 92.2
smoothie_dict["Fiber"] = 10.2
smoothie_dict["Sugars"] = 66.9 + 37.5
smoothie_dict["Protein"] = 30.7
smoothie_dict["Calcium"] = 870/1000
smoothie_dict["Iron"] = 3/1000
smoothie_dict["Potassium"] = 1205.7/1000
smoothie_dict["Vitamin D"] = 0
smoothie_dict["Weight"] = 665.1

In [167]:
vanilla_almond_milk_file = "vanilla_almond_milk_by_topco_associates_inc.csv"
vanilla_almond_milk_dict = overall_dict.copy()
reader(vanilla_almond_milk_file,vanilla_almond_milk_dict,desired_serving)

frozen_blueberries_file = "blueberries_frozen.csv"
frozen_blueberries_dict = overall_dict.copy()
reader(frozen_blueberries_file,frozen_blueberries_dict,desired_serving)

frozen_strawberries_file = "strawberries_frozen.csv"
frozen_strawberries_dict = overall_dict.copy()
reader(frozen_strawberries_file,frozen_strawberries_dict,desired_serving)

banana_file = "banana_raw.csv"
banana_dict = overall_dict.copy()
reader(banana_file,banana_dict,desired_serving)

isopure_zero_carb_file = "isopure_zero_carb_protein_creamy_vanilla.csv"
isopure_zero_carb_dict = overall_dict.copy()
reader(isopure_zero_carb_file,isopure_zero_carb_dict,desired_serving)

granola_homemade_file = "granola_homemade.csv"
granola_homemade_dict = overall_dict.copy()
reader(granola_homemade_file,granola_homemade_dict,desired_serving)

honey_file = "honey.csv"
honey_dict = overall_dict.copy()
reader(honey_file,honey_dict,desired_serving)

smoothie_ingredient_list = [vanilla_almond_milk_dict, frozen_blueberries_dict, frozen_strawberries_dict, banana_dict, isopure_zero_carb_dict, granola_homemade_dict, honey_dict]


In [168]:
running_tf(smoothie_ingredient_list,smoothie_dict,key_list)

<tf.Variable 'Variable:0' shape=(7,) dtype=float32, numpy=
array([271.92798 , 196.73726 ,  69.600945,  65.63423 ,  35.12482 ,
        19.13118 ,   6.943507], dtype=float32)>
665.09985


[267.6542053222656,
 193.63507080078125,
 65.10347747802734,
 64.10382843017578,
 28.462602615356445,
 21.039901733398438,
 31.2152156829834]

In [169]:
running_tf(smoothie_ingredient_list,smoothie_dict,key_list)

<tf.Variable 'Variable:0' shape=(7,) dtype=float32, numpy=
array([151.26909 , 145.85268 , 141.86902 , 102.03573 ,  76.58154 ,
        24.314064,  23.17786 ], dtype=float32)>
665.1


[152.32650756835938,
 147.1532440185547,
 142.36123657226562,
 103.30818939208984,
 57.0115966796875,
 22.126388549804688,
 39.401920318603516]

In [ ]:
actual = [244,138,132,68,31,30,21]